### ISSUE TITLE
document.featurePolicy vs document.permissionsPolicy

### ISSUE THREAD

**Issue by evilpie** [w3c/webappsec-permissions-policy#507] opened 2023-01-16 15:20 UTC
I looked a bit into the implementation status of the Permissions Policy in Firefox compared to other browsers. In the spec the name of the accessor was changed to `permissionsPolicy`, but I still see `featurePolicy` in Chrome.

How far along is the renaming overall? Are there any known web compat issues with featurePolicy vs permissionsPolicy?

**Comment by annevk** [comment] 2023-01-16 15:56
This is a duplicate of #401. As I argued there I don't think we should add this API at all and instead use the existing Permissions API.

**Closed by annevk** 2023-01-16 15:56 UTC

**Comment by evilpie** [comment] 2023-01-16 16:02
Thanks Anne!
