### ISSUE TITLE
support <meta http-equiv> mechanism to set the policy

### ISSUE THREAD

**Issue by justadreamer** [w3c/webappsec-permissions-policy#506] opened 2023-01-13 13:11 UTC
There once was an issue #15 that enabled delivery of the Permissions Policy via meta http-equiv attribute.  Useful for the case when one can not modify server response headers to set the policy (f.e. hosting on pages.github.io does not allow that).  
 The spec does not mention meta http-equiv attribute as a way to deliver Permissions-Policy.  I can't find historically whether and when a decision was made explicitly to not support it as a delivery mechanism.  Can this delivery mechanism be supported as well?

**Comment by justadreamer** [comment] 2023-01-13 13:16
A little more background: `Permissions-Policy` header is needed to delegate processing of Client-Hints to the 3rd party. 
 `Accept-CH` header is also necessary to ask the user agent to send the client hint headers in the next request either to the 1st or allowed 3rd party.  `Accept-CH` can be delivered via <meta http-equiv>, while `Permissions-Policy` can't, thus delegation to 3rd party processing seems handicapped.

**Comment by annevk** [comment] 2023-01-13 13:31
Duplicate of #55.

**Closed by annevk** 2023-01-13 13:31 UTC
